version: '3.8'

services:
  legocarla:
    image: jiapengzhao/lego_carla_server:ogRepo
    container_name: carla_server
    command: ["/bin/bash", "/home/CARLA_0.9.15/CarlaUE4.sh", "-RenderOffScreen"]
    ports:
      - "2000-2002:2000-2002"
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute, graphics, utility
      - QT_X11_NO_MITSHM=1
      - SDL_VIDEODRIVER=x11
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ${HOME}/.Xauthority:/root/.Xauthority:rw
      # - /etc/group:/etc/group:ro
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/shadow:/etc/shadow:ro
      # - /etc/sudoers:/etc/sudoers:ro
      # - /etc/sudoers.d:/etc/sudoers.d:ro
      # - /home/${USER}:/home/${USER}:rw #share your home with write permissions
    # network_mode: "host" #kubernetes does not have network_mode=host?, commenting this and mounting x11-unix seems to resolve problem
    stdin_open: true
    tty: true
